<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ThisNetWorks.OrchardCore.GoogleMaps</PackageId>
    <Title>GoogleMaps for Orchard Core</Title>
    <Description>GoogleMaps for Orchard Core</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" Version="2.2.0" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="2.2.0" />
    <PackageReference Include="OrchardCore.ContentTypes.Abstractions" Version="2.2.0" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="2.2.0" />
    <PackageReference Include="OrchardCore.Navigation.Core" Version="2.2.0" />
    <PackageReference Include="OrchardCore.ResourceManagement" Version="2.2.0" />
    <PackageReference Include="OrchardCore.Settings" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.8" />
    <PackageReference Include="System.Text.Json" Version="9.0.8" />
  </ItemGroup>

</Project>
